#!/usr/bin/env python3
"""Generate the /en/ and /ja/ language pages from index.html.

index.html is the source of truth: it holds the whole app (inline Vue) plus the
Chinese SEO copy. This script clones it per language, swapping only the three
marked regions in the head/body and rewriting <html lang>.

Two things make a subdirectory copy work without touching any app code:

  * <base href="/"> — every asset in index.html is referenced relatively
    ("app.css?v=", fetch('models/...'), new Worker('wasmFallbackWorker.js'),
    the dynamically injected WASM backend <script>). They all resolve against
    the document base URL, so one <base> tag fixes the lot.
  * window.__PAGE_LANG__ — getInitialLanguage() prefers it over the saved
    preference, so /en/ opens in English even for a visitor whose last choice
    was Chinese.

Run after editing index.html:  python3 build_pages.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SITE = "https://realcugan.lemonno.xyz"

# ---------------------------------------------------------------- head meta --

META = {
    "en": f"""    <!-- I18N:META:START — generated by build_pages.py; keep in sync with i18n.js -->
    <title>REAL-CUGAN SUPER·RESOLUTION</title>
    <meta name="force-rendering" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta name="description" content="Free online Real-CUGAN anime image upscaler. Enlarge anime art, illustrations and line art 2×-4× locally in your browser with WebAssembly — nothing is uploaded.">
    <meta name="theme-color" content="#120a18">
    <link rel="canonical" href="{SITE}/en/">
    <link rel="alternate" hreflang="zh-Hans" href="{SITE}/">
    <link rel="alternate" hreflang="en" href="{SITE}/en/">
    <link rel="alternate" hreflang="ja" href="{SITE}/ja/">
    <link rel="alternate" hreflang="x-default" href="{SITE}/">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Real-CUGAN">
    <meta property="og:locale" content="en_US">
    <meta property="og:title" content="Free online Real-CUGAN anime image upscaler">
    <meta property="og:description" content="Images are processed locally in your browser and never uploaded. 2×, 3× and 4× anime upscaling with selectable denoise levels.">
    <meta property="og:url" content="{SITE}/en/">
    <meta property="og:image" content="{SITE}/social-preview.jpg">
    <meta property="og:image:secure_url" content="{SITE}/social-preview.jpg">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:image:alt" content="Real-CUGAN anime image upscaling before and after comparison">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Free online Real-CUGAN anime image upscaler">
    <meta name="twitter:description" content="Images are processed locally in your browser and never uploaded. 2×, 3× and 4× anime upscaling with selectable denoise levels.">
    <meta name="twitter:image" content="{SITE}/social-preview.jpg">
    <!-- I18N:META:END -->""",
    "ja": f"""    <!-- I18N:META:START — generated by build_pages.py; keep in sync with i18n.js -->
    <title>REAL-CUGAN 超·解像</title>
    <meta name="force-rendering" content="webkit" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta name="description" content="無料のオンライン Real-CUGAN アニメ画像超解像ツール。WebAssembly でブラウザー内のまま、アニメ・イラスト・線画を 2×〜4× に拡大します。画像はアップロードされません。">
    <meta name="theme-color" content="#120a18">
    <link rel="canonical" href="{SITE}/ja/">
    <link rel="alternate" hreflang="zh-Hans" href="{SITE}/">
    <link rel="alternate" hreflang="en" href="{SITE}/en/">
    <link rel="alternate" hreflang="ja" href="{SITE}/ja/">
    <link rel="alternate" hreflang="x-default" href="{SITE}/">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Real-CUGAN">
    <meta property="og:locale" content="ja_JP">
    <meta property="og:title" content="無料オンライン Real-CUGAN アニメ画像超解像">
    <meta property="og:description" content="画像はブラウザー内で処理され、サーバーへ送信されません。2倍・3倍・4倍の拡大と複数段階のノイズ除去に対応。">
    <meta property="og:url" content="{SITE}/ja/">
    <meta property="og:image" content="{SITE}/social-preview.jpg">
    <meta property="og:image:secure_url" content="{SITE}/social-preview.jpg">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:image:alt" content="Real-CUGAN アニメ画像超解像の処理前後比較">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="無料オンライン Real-CUGAN アニメ画像超解像">
    <meta name="twitter:description" content="画像はブラウザー内で処理され、サーバーへ送信されません。2倍・3倍・4倍の拡大と複数段階のノイズ除去に対応。">
    <meta name="twitter:image" content="{SITE}/social-preview.jpg">
    <!-- I18N:META:END -->""",
}

# ------------------------------------------------------------- JSON-LD graph --

def jsonld(lang, page_url, page_lang, name, desc, site_desc, caption):
    return f"""<!-- I18N:JSONLD:START — generated by build_pages.py -->
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@graph": [
    {{
      "@type": "WebSite",
      "@id": "{SITE}/#website",
      "url": "{SITE}/",
      "name": "Real-CUGAN",
      "description": {_j(site_desc)},
      "inLanguage": ["zh-CN", "en", "ja"]
    }},
    {{
      "@type": "WebPage",
      "@id": "{page_url}#webpage",
      "url": "{page_url}",
      "name": {_j(name)},
      "description": {_j(desc)},
      "inLanguage": "{page_lang}",
      "isPartOf": {{ "@id": "{SITE}/#website" }},
      "primaryImageOfPage": {{
        "@type": "ImageObject",
        "url": "{SITE}/social-preview.jpg",
        "width": 1200,
        "height": 630,
        "caption": {_j(caption)}
      }}
    }},
    {{
      "@type": "SoftwareApplication",
      "@id": "{SITE}/#app",
      "name": "Real-CUGAN",
      "operatingSystem": "Web",
      "applicationCategory": "GraphicsApplication",
      "offers": {{ "@type": "Offer", "price": "0", "priceCurrency": "USD" }},
      "url": "{SITE}/",
      "description": {_j(desc)},
      "softwareVersion": "{APP_VERSION}",
      "image": "{SITE}/social-preview.jpg"
    }}
  ]
}}
</script>
<!-- I18N:JSONLD:END -->"""


def _j(s):
    import json
    return json.dumps(s, ensure_ascii=False)


# ------------------------------------------------------------- SEO body copy --

SEO_EN = """    <!-- I18N:SEO:START — one language per URL; regenerated by build_pages.py -->
    <section class="seo-content" aria-label="Real-CUGAN introduction">
        <article class="seo-copy" lang="en" aria-labelledby="seo-title-en">
            <p class="seo-kicker">LOCAL AI IMAGE UPSCALER</p>
            <h1 id="seo-title-en">Free online Real-CUGAN anime image upscaler</h1>
            <p class="seo-lead">Real-CUGAN enlarges anime art, illustrations, and line art at 2×, 3×, or 4× in your browser. It restores lines, flat-color detail, and compression damage locally through WebAssembly; images are never uploaded.</p>
            <div class="seo-prose">
                <h2>Choosing between the SE and Pro models</h2>
                <p><strong>SE</strong> supports 2×, 3×, and 4×, so choose it whenever you need 4×. <strong>Pro</strong> supports 2× and 3× and is a good first choice when you want more natural-looking lines and flat-color transitions.</p>
                <h2>What the denoise levels actually do</h2>
                <p>Use <strong>none</strong> for clean originals, <strong>conservative</strong> when you want to preserve style and texture, and <strong>denoise 1/2</strong> for light compression on SE at 2×. Use <strong>denoise 3</strong> only for obvious noise or block artifacts; stronger denoise can flatten fine detail.</p>
            </div>

            <p class="seo-langnav">Other languages:
                <a href="/" hreflang="zh-Hans" lang="zh-CN">中文</a> ·
                <a href="/ja/" hreflang="ja" lang="ja">日本語</a>
            </p>
        </article>
    </section>
    <!-- I18N:SEO:END -->
"""

SEO_JA = """    <!-- I18N:SEO:START — one language per URL; regenerated by build_pages.py -->
    <section class="seo-content" aria-label="Real-CUGAN introduction">
        <article class="seo-copy" lang="ja" aria-labelledby="seo-title-ja">
            <p class="seo-kicker">LOCAL AI IMAGE UPSCALER</p>
            <h1 id="seo-title-ja">無料オンライン Real-CUGAN アニメ画像超解像</h1>
            <p class="seo-lead">Real-CUGAN はアニメ、イラスト、線画をブラウザー内で 2倍・3倍・4倍に拡大します。WebAssembly により線や色面、圧縮劣化を端末内で補正し、画像はアップロードされません。</p>
            <div class="seo-prose">
                <h2>SE と Pro、どちらのモデルを選ぶか</h2>
                <p><strong>SE</strong> は 2倍・3倍・4倍に対応するため、4倍が必要なら SE を選びます。<strong>Pro</strong> は 2倍・3倍に対応し、線や色面をより自然に仕上げたいときの最初の選択肢です。</p>
                <h2>ノイズ除去レベルの実際の違い</h2>
                <p>きれいな画像は<strong>なし</strong>、画風や質感を残したい場合は<strong>保守的</strong>を選びます。軽い圧縮ノイズには<strong>レベル 1/2</strong>（SE の 2倍のみ）、目立つノイズやブロック状の劣化には<strong>レベル 3</strong>を使います。強い設定ほど細部が平坦になる場合があります。</p>
            </div>

            <p class="seo-langnav">他の言語:
                <a href="/" hreflang="zh-Hans" lang="zh-CN">中文</a> ·
                <a href="/en/" hreflang="en" lang="en">English</a>
            </p>
        </article>
    </section>
    <!-- I18N:SEO:END -->
"""

# ------------------------------------------------------------------- builder --

def replace_marked(html, start, end, replacement):
    i = html.index(start)
    j = html.index(end, i) + len(end)
    return html[:i] + replacement + html[j:]


def build(src, lang, html_lang, meta, jsonld_block, seo):
    out = src
    out = re.sub(r'<html lang="[^"]*">', f'<html lang="{html_lang}">', out, count=1)
    out = replace_marked(out, "<!-- I18N:META:START", "<!-- I18N:META:END -->", meta)
    out = replace_marked(out, "<!-- I18N:JSONLD:START", "<!-- I18N:JSONLD:END -->", jsonld_block)
    out = replace_marked(out, "<!-- I18N:SEO:START", "<!-- I18N:SEO:END -->", seo.rstrip("\n"))
    # <base> must precede every relative URL in the document, and __PAGE_LANG__
    # must be set before the app script reads it.
    anchor = '<meta charset="utf-8">'
    inject = (
        anchor
        + '\n    <!-- Served from a subdirectory: resolve every relative asset, model'
        + '\n         fetch and Worker URL against the site root instead of /' + lang + '/. -->'
        + '\n    <base href="/">'
        + f'\n    <script>window.__PAGE_LANG__ = "{lang}";</script>'
    )
    if anchor not in out:
        sys.exit("index.html: <meta charset=\"utf-8\"> anchor not found")
    out = out.replace(anchor, inject, 1)
    return out


src = (ROOT / "index.html").read_text(encoding="utf-8")

m = re.search(r"const APP_VERSION = '([^']+)'", src)
if not m:
    sys.exit("index.html: APP_VERSION not found")
APP_VERSION = m.group(1)

PAGES = {
    "en": dict(
        html_lang="en",
        jsonld=lambda: jsonld(
            "en", f"{SITE}/en/", "en",
            "Free Online Anime Image Upscaler - Real-CUGAN",
            "Enlarge anime art, illustrations and line art 2×-4× locally in the browser with WebAssembly. Denoising included, nothing uploaded.",
            "Free online anime image upscaler that runs entirely in the browser — no upload required.",
            "Real-CUGAN anime image upscaling before and after comparison"),
        seo=lambda: SEO_EN,
    ),
    "ja": dict(
        html_lang="ja",
        jsonld=lambda: jsonld(
            "ja", f"{SITE}/ja/", "ja",
            "無料オンラインアニメ画像超解像 - Real-CUGAN",
            "WebAssembly でブラウザー内のまま、アニメ・イラスト・線画を 2×〜4× に拡大。ノイズ除去にも対応し、アップロードは不要です。",
            "ブラウザー内で完結する無料のアニメ画像超解像ツール。アップロードは不要です。",
            "Real-CUGAN アニメ画像超解像の処理前後比較"),
        seo=lambda: SEO_JA,
    ),
}

for lang, cfg in PAGES.items():
    html = build(src, lang, cfg["html_lang"], META[lang], cfg["jsonld"](), cfg["seo"]())
    target = ROOT / lang / "index.html"
    target.parent.mkdir(exist_ok=True)
    target.write_text(html, encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)}  ({len(html):,} bytes)")

print(f"source index.html      ({len(src):,} bytes, APP_VERSION={APP_VERSION})")
